# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI



on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env: 
  DATABASE_URL : postgres://uycdxfchziegmd:45054b04a05372b0a6ceed96f3fbdd5a817b55fa7157f3bbaa8aa2762091c1cc@ec2-99-81-16-126.eu-west-1.compute.amazonaws.com:5432/dctk9qlskj2t18

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x, 16.x, 17.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
